### ISSUE TITLE
Criar páginas

### ISSUE THREAD

**Issue by ftonato** [rodkulman/modelo-de-processos#9]
### Concluído
- [x] Categoria - @ftonato
- [x] Prática Específica - @ftonato
- [x] Nível de Maturidade - @ftonato
- [x] Modelo - @ftonato
- [x] Meta Específica - @ftonato
- [x] Produto Trabalho - @ftonato

**Comment by WLottermann** [comment]
### Concluído
- [x] Área de Processo - @WLottermann
- [x] Meta Genérica - @WLottermann
- [x] Nível de Capacidade - @WLottermann
